---

- name: Install nfs-kernel-server
  become: true
  ansible.builtin.apt:
    name: [ "nfs-kernel-server" ]
    state: present

- name: Start and enabled
  become: true
  ansible.builtin.service:
    name: nfs-kernel-server
    state: started
    enabled: yes
