---

- name: Import install tasks
  ansible.builtin.import_tasks: install.yml
- name: Import configure tasks
  ansible.builtin.import_tasks: configure.yml
- name: Import nfs exports tasks
  ansible.builtin.import_tasks: nfs_exports.yml
