---

groups:
  - name: Services
    rules:
      - alert: ApacheDown
        expr: node_systemd_unit_state{name="apache2.service", state="active"} != 1
        labels:
          severity: "critical"
        annotations:
          summary: "Apache is down (instance {{ $labels.instance }})"
          description: "Apache is down \n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

      - alert: MedusaDown
        expr: node_systemd_unit_state{name="medusa.service", state="active"} != 1
        labels:
          severity: "critical"
        annotations:
          summary: "medusa is down (instance {{ $labels.instance }})"
          description: "medusa is down \n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

      - alert: openvpnDown
        expr: node_systemd_unit_state{name=~"openvpn.+", state="active"} != 1
        labels:
          severity: "critical"
        annotations:
          summary: "openvpn is down (instance {{ $labels.instance }})"
          description: "openvpn is down \n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

      - alert: SabnzbdDown
        expr: node_systemd_unit_state{name="sabnzbdplus.service", state="active"} != 1
        labels:
          severity: "critical"
        annotations:
          summary: "sabnzbdplus is down (instance {{ $labels.instance }})"
          description: "sabnzbdplus is down \n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

      - alert: TransmissionDown
        expr: node_systemd_unit_state{name="transmission-daemon.service", state="active"} != 1
        labels:
          severity: "critical"
        annotations:
          summary: "transmission is down (instance {{ $labels.instance }})"
          description: "transmission is down \n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

      - alert: NfsKernlerServerDown
        expr: node_nfsd_server_threads == 0
        labels:
          severity: "critical"
        annotations:
          summary: "Total number of NFSd kernel threads is 0 (instance {{ $labels.instance }})"
          description: "NFSd kernel threads is 0 \n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
