---

- name: create prometheus_alertmanager configuration directories
  become: true
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ prometheus_alertmanager_user }}"
    group: "{{ prometheus_alertmanager_group }}"
    mode: 0755
  loop:
    - "{{ prometheus_alertmanager_config_path }}"
    - "{{ prometheus_alertmanager_data_path }}"
    - "{{ prometheus_alertmanager_amtool_config_path }}"
    - "{{ prometheus_alertmanager_gotify_bridge_path }}"

- name: configure amtool
  become: true
  template:
    src: "amtool.yml.j2"
    dest: "{{ prometheus_alertmanager_amtool_config_file_path }}"
    owner: "{{ prometheus_alertmanager_user }}"
    group: "{{ prometheus_alertmanager_group }}"
    mode: 0640

- name: configure alertmanager.yml
  become: true
  template:
    src: "alertmanager.yml.j2"
    dest: "{{ prometheus_alertmanager_config_path }}/alertmanager.yml"
    owner: "{{ prometheus_alertmanager_user }}"
    group: "{{ prometheus_alertmanager_group }}"
    mode: 0640
    validate: "{{ prometheus_alertmanager_install_path }}/amtool check-config %s"
  notify: restart prometheus_alertmanager
