---

- name: create alertmanager/amtool config path
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ prometheus_alertmanager_user }}"
    group: "{{ prometheus_alertmanager_group }}"
    mode: 0770
  loop:
    - "{{ prometheus_alertmanager_config_path }}"
    - "{{ prometheus_alertmanager_amtool_config_path }}"

- name: configure amtool
  become: yes
  become_user: "{{ prometheus_alertmanager_user }}"
  template:
    src: "amtool.yml.j2"
    dest: "{{ prometheus_alertmanager_amtool_config_file_path }}"
    group: "{{ prometheus_alertmanager_group }}"
    mode: 0640

- name: configure alertmanager
  become: yes
  become_user: "{{ prometheus_alertmanager_user }}"
  template:
    src: "alertmanager.yml.j2"
    dest: "{{ prometheus_alertmanager_config_file_path }}"
    group: "{{ prometheus_alertmanager_group }}"
    mode: 0640
    validate: "{{ prometheus_alertmanager_home }}/amtool check-config %s"
  notify: reload alertmanager
