---

- include_tasks: setup.yml
- include_tasks: version_check.yml
- include_tasks: install_alertmanager.yml
  when: install_prometheus_alertmanager
- include_tasks: install_alertmanager_gotify_bridge.yml
  when: install_prometheus_alertmanager_gotify_bridge
- include_tasks: configure.yml
- include_tasks: service.yml
