---

- name: create prometheus_alertmanager group
  become: yes
  group:
    name: "{{ prometheus_alertmanager_group }}"
    system: yes
    state: present

- name: create prometheus_alertmanager user
  become: yes
  user:
    name: "{{ prometheus_alertmanager_user }}"
    shell: "/usr/sbin/nologin"
    system: yes
    group: "{{ prometheus_alertmanager_group }}"
    create_home: no
    home: "{{ prometheus_alertmanager_install_path }}"

- name: create prometheus_alertmanager base paths
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  loop:
    - "{{ prometheus_alertmanager_base_path }}"
    - "{{ prometheus_alertmanager_base_config_path }}"
