---

# apache_vhosts role
required_apache_vhosts: [ "prometheus", "grafana" ]

# prometheus role
prometheus_blackbox_targets:
  - url: "transmission.{{ top_lvl_domain }}"
    job: "blackbox"
  - url: "sabnzbd.{{ top_lvl_domain }}"
    job: "blackbox"
  - url: "medusa.{{ top_lvl_domain }}"
    job: "blackbox"
prometheus_alerting_rules:
  - group_name: applications
    rules:
      - name: "application"
        expr: "probe_success{job=\"blackbox\"} == 0"
        severity: "critical"
        summary: "Application is down"
prometheus_alertmanagers: ["localhost:9093"]
