---

# apache_vhosts role
apache_vhosts_config:
  - { name: "grafana", server_name: "{{ grafana_url }}", listen_port: "{{ grafana_listen_port }}", enable_ssl: true }
  - { name: "prometheus", server_name: "{{ prometheus_url }}", listen_port: "{{ prometheus_listen_port }}", enable_ssl: true }
  - { name: "prometheus_alertmanager", server_name: "{{ prometheus_alertmanager_web_external_url }}", listen_port: "{{ prometheus_alertmanager_listen_port }}", enable_ssl: true }

# prometheus role
prometheus_metrics_job_targets:
  - 10.1.1.1
  - kodi.local
  - azmodan.local
prometheus_metrics_job_relabel_configs:
  - source_labels: "[__address__]"
    regex: 10\\.1\\.1\\.1(.*)
    replacement: openwrt
    target_label: instance
prometheus_blackbox_exporter_targets:
  - url: "transmission.{{ top_lvl_domain }}"
    instance: "transmission"
    job: "blackbox"
  - url: "sabnzbd.{{ top_lvl_domain }}"
    instance: "sabnzbd"
    job: "blackbox"
  - url: "medusa.{{ top_lvl_domain }}"
    instance: "medusa"
    job: "blackbox"
