---

# apache_vhosts role
required_apache_vhosts: [ "prometheus", "prometheus_alertmanager", "grafana" ]

# prometheus role
prometheus_blackbox_targets:
  - url: "transmission.{{ top_lvl_domain }}"
    job: "blackbox"
  - url: "sabnzbd.{{ top_lvl_domain }}"
    job: "blackbox"
  - url: "medusa.{{ top_lvl_domain }}"
    job: "blackbox"
