---

- name: configure Grafana
  become: yes
  replace:
    path: "{{ grafana_config_path }}/grafana.ini"
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  loop:
    - { regexp: '^;?root_url(.*)', replace: 'root_url = {{ grafana_config_root_url }}' }
    - { regexp: '^;?admin_user(.*)', replace: 'admin_user = {{ grafana_admin_user }}' }
    - { regexp: '^;?admin_password(.*)', replace: 'admin_password = {{ grafana_admin_password }}' }
    - { regexp: '^;?http_port(.*)', replace: 'http_port = {{ grafana_http_port }}' }
  notify: restart grafana

- name: template the datasources
  become: yes
  template:
    src: datasources.yml.j2
    dest: "{{ grafana_config_path }}/provisioning/datasources/datasources.yml"
    group: "grafana"
    mode: "0640"
  notify: restart grafana

- name: enable and start grafana
  become: yes
  service:
    name: grafana-server
    state: started
    enabled: yes
