---

- name: Configure Grafana ini file
  become: true
  ansible.builtin.replace:
    path: "{{ grafana_config_path }}/grafana.ini"
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  loop: "{{ grafana_config_settings }}"
  notify: Restart grafana

- name: Template the datasources
  become: true
  ansible.builtin.template:
    src: datasources.yaml.j2
    dest: "{{ grafana_config_path }}/provisioning/datasources/datasources.yaml"
    group: "{{ grafana_group }}"
    mode: "0640"
  notify: Restart grafana

- name: Template the dashboards
  become: true
  ansible.builtin.template:
    src: dashboards.yaml.j2
    dest: "{{ grafana_config_path }}/provisioning/dashboards/dashboards.yaml"
    group: "{{ grafana_group }}"
    mode: "0640"
  notify: Restart grafana

- name: Create the dashboards config path
  become: true
  ansible.builtin.file:
    state: directory
    group: "{{ grafana_group }}"
    path: "{{ grafana_dashboards_config_path }}"
    mode: "0755"

- name: Create the dashboards paths
  become: true
  ansible.builtin.file:
    state: directory
    group: "{{ grafana_group }}"
    path: "{{ item.dest }}"
    mode: "0755"
  loop: "{{ grafana_dashboards }}"

- name: Copy the dashboards
  become: true
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    group: "{{ grafana_group }}"
    mode: "0755"
  loop: "{{ grafana_dashboards }}"
  notify: Restart grafana

- name: Enable and start grafana
  become: true
  ansible.builtin.service:
    name: grafana-server
    state: started
    enabled: yes
