---

- name: configure Grafana
  become: yes
  replace:
    path: "{{ grafana_config_path }}/grafana.ini"
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  loop: "{{ grafana_config_settings }}"
  notify: restart grafana

- name: template the datasources
  become: yes
  template:
    src: datasources.yml.j2
    dest: "{{ grafana_config_path }}/provisioning/datasources/datasources.yml"
    group: "grafana"
    mode: "0640"
  notify: restart grafana

- name: enable and start grafana
  become: yes
  service:
    name: grafana-server
    state: started
    enabled: yes
