---

- name: install required packages
  become: yes
  apt:
    name: [ "adduser", "libfontconfig" ]
    state: present

- name: install grafana
  become: yes
  apt:
    name: "grafana"
    state: present
