---

- name: Install required packages
  become: true
  ansible.builtin.apt:
    name: "{{ grafana_required_packages }}"
    state: present

- name: Add Grafana apt signing key
  become: true
  ansible.builtin.apt_key:
    url: "{{ grafana_apt_key_url }}"
    state: present

- name: Add Grafana repositories
  become: true
  ansible.builtin.apt_repository:
    repo: "{{ grafana_apt_repo_url }}"
    state: present
