---

- name: ensure apt-transport-https is installed
  become: yes
  apt:
    name: "apt-transport-https"
    state: present

- name: Add Grafana apt signing key
  become: yes
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: Add Grafana repositories
  become: yes
  apt_repository:
    repo: "deb https://packages.grafana.com/oss/deb stable main"
    state: present
