---

- name: Restart openvpn
  become: true
  ansible.builtin.service:
    name: openvpn
    state: restarted
  listen: restart openvpn

- name: Restart openvpn
  become: true
  ansible.builtin.service:
    name: "openvpn@{{ openvpn_name }}"
    state: restarted
  listen: restart openvpn
