---

- name: restart openvpn
  become: true
  service:
    name: openvpn
    state: restarted
  listen: restart openvpn

- name: restart openvpn {{ openvpn_name }}
  become: true
  service:
    name: "openvpn@{{ openvpn_name }}"
    state: restarted
  listen: restart openvpn
