---

transmission_group: "debian-transmission"
transmission_user: "debian-transmission"
transmission_user_home: "/opt/transmission"
transmission_settings_file_path: "{{ transmission_user_home }}/.config/transmission-daemon/settings.json"
transmission_url: "transmission.{{ top_lvl_domain }}"
transmission_listen_port: 9091

# settings.json variables
transmission_rpc_username: "\"transmission\""
transmission_rpc_password: "\"transmission\""
transmission_settings_alt_speed_down: 500
transmission_settings_alt_speed_up: 1
transmission_settings_download_dir: "\"{{ transmission_user_home }}/completed\""
transmission_settings_encryption: 2
transmission_settings_incomplete_dir: "\"{{ transmission_user_home }}/incomplete\""
transmission_settings_incomplete_dir_enabled: "true"
transmission_rpc_host_whitelist_enabled: "false"
transmission_rpc_whitelist_enabled: "false"
transmission_settings:
  - option: "\"rpc-username\""
    value: "{{ transmission_rpc_username }}"
  - option: "\"rpc-password\""
    value: "{{ transmission_rpc_password }}"
  - option: "\"alt-speed-down\""
    value: "{{ transmission_settings_alt_speed_down }}"
  - option: "\"alt-speed-up\""
    value: "{{ transmission_settings_alt_speed_up }}"
  - option: "\"download-dir\""
    value: "{{ transmission_settings_download_dir }}"
  - option: "\"encryption\""
    value: "{{ transmission_settings_encryption }}"
  - option: "\"incomplete-dir\""
    value: "{{ transmission_settings_incomplete_dir }}"
  - option: "\"incomplete-dir-enabled\""
    value: "{{ transmission_settings_incomplete_dir_enabled }}"
  - option: "\"rpc-host-whitelist-enabled\""
    value: "{{ transmission_rpc_host_whitelist_enabled }}"
  - option: "\"rpc-whitelist-enabled\""
    value: "{{ transmission_rpc_whitelist_enabled }}"
