---

# apache_vhosts role
apache_vhosts_config:
  - name: "grafana"
    server_name: "{{ grafana_url }}"
    listen_port: "{{ grafana_listen_port }}"
    enable_ssl: true
    template: "proxy_pass"
  - name: "prometheus"
    server_name: "{{ prometheus_url }}"
    listen_port: "{{ prometheus_listen_port }}"
    enable_ssl: true
    template: "proxy_pass"
  - name: "prometheus_alertmanager"
    server_name: "{{ prometheus_alertmanager_web_external_url }}"
    listen_port: "{{ prometheus_alertmanager_listen_port }}"
    enable_ssl: true
    template: "proxy_pass"

# prometheus role
prometheus_metrics_job_targets:
  - 10.1.1.1
  - merovingian.local
  - morpheus.local
  - neo.local
  - link.local
#  - kodi.local
#  - azmodan.local
prometheus_metrics_job_relabel_configs:
  - source_labels: "[__address__]"
    regex: 10\\.1\\.1\\.1(.*)
    replacement: openwrt
    target_label: instance
prometheus_blackbox_exporter_targets:
  - url: "{{ gotify_url }}"
    instance: "gotify"
    job: "blackbox"
  - url: "{{ grafana_url }}"
    instance: "grafana"
    job: "blackbox"
  - url: "{{ medusa_url }}"
    instance: "medusa"
    job: "blackbox"
  - url: "{{ miniflux_url }}"
    instance: "miniflux"
    job: "blackbox"
  - url: "{{ prometheus_url }}"
    instance: "prometheus"
    job: "blackbox"
  - url: "{{ prometheus_alertmanager_web_external_url }}"
    instance: "prometheus_alertmanager"
    job: "blackbox"
  - url: "{{ sabnzbd_url }}"
    instance: "sabnzbd"
    job: "blackbox"
  - url: "{{ transmission_url }}"
    instance: "transmission"
    job: "blackbox"

# prometheus_alertmanager
prometheus_alertmanager_gotify_endpoint: "https://{{ gotify_url }}/message"
