---

pihole_custom_dns_entries:
  - ip: 10.1.1.200
    url: "{{ grafana_url }}"
  - ip: 10.1.1.200
    url: "{{ prometheus_url }}"
  - ip: 10.1.1.200
    url: "{{ prometheus_alertmanager_web_external_url }}"
  - ip: 10.1.1.201
    url: "{{ miniflux_url }}"
  - ip: 10.1.1.202
    url: "{{ medusa_url }}"
  - ip: 10.1.1.203
    url: "{{ sabnzbd_url }}"
  - ip: 10.1.1.203
    url: "{{ transmission_url }}"
