---

# apache_vhosts role
apache_vhosts_config:
  - { name: "pihole", server_name: "{{ pihole_url }}", enable_ssl: true, template: "document_root", document_root: "/var/www/html/admin/" }
  - { name: "gotify", server_name: "{{ gotify_url }}", listen_port: "{{ gotify_listen_port }}", enable_ssl: true, template: "proxy_pass" }

# pihole
pihole_custom_dns_entries:
  - ip: 10.1.1.200
    url: "{{ grafana_url }}"
  - ip: 10.1.1.200
    url: "{{ prometheus_url }}"
  - ip: 10.1.1.200
    url: "{{ prometheus_alertmanager_web_external_url }}"
  - ip: 10.1.1.201
    url: "{{ miniflux_url }}"
  - ip: 10.1.1.202
    url: "{{ medusa_url }}"
  - ip: 10.1.1.203
    url: "{{ sabnzbd_url }}"
  - ip: 10.1.1.203
    url: "{{ transmission_url }}"
  - ip: 10.1.1.204
    url: "{{ pihole_url }}"
  - ip: 10.1.1.204
    url: "{{ gotify_url }}"
