---

- name: enable modules
  become: yes
  apache2_module:
    state: present
    name: "{{ item }}"
  loop:
    - autoindex
    - deflate
    - expires
    - filter
    - headers
    - include
    - mime
    - rewrite
    - setenvif
    - ssl
    - proxy_html
    - proxy_http
    - xml2enc
  notify: reload apache

- name: configure the security settings
  become: yes
  lineinfile:
    dest: "/etc/apache2/conf-available/security.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  loop:
    - { regexp: '^ServerTokens', line: 'ServerTokens Prod' }
    - { regexp: '^ServerSignature', line: 'ServerSignature Off' }
  notify: reload apache

- name: configure the ssl settings
  become: yes
  lineinfile:
    dest: "/etc/apache2/mods-available/ssl.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  loop:
    - { regexp: '^SSLCipherSuite', line: 'SSLCipherSuite HIGH:!aNULL:!SHA1' }
  notify: reload apache

- name: configure the hostname settings
  become: yes
  lineinfile:
    dest: "/etc/apache2/conf-available/hostname.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    create: yes
  loop:
    - { regexp: '^ServerName', line: 'ServerName {{ ansible_hostname }}' }
  notify: reload apache

- name: enable the hostname configs
  become: yes
  file:
    src: "/etc/apache2/conf-available/hostname.conf"
    dest: "/etc/apache2/conf-enabled/hostname.conf"
    state: link
  notify: reload apache

- name: change the listen ports to 0.0.0.0
  become: yes
  replace:
    path: "/etc/apache2/ports.conf"
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  loop:
    - { regexp: 'Listen 80', replace: 'Listen 0.0.0.0:80' }
    - { regexp: 'Listen 443', replace: 'Listen 0.0.0.0:443' }
  notify: reload apache

- name: enable apache2 and start it
  become: yes
  service:
    name: apache2
    state: started
    enabled: yes
