---

- name: Enable modules
  become: true
  community.general.apache2_module:
    state: present
    name: "{{ item }}"
  loop: "{{ apache_modules }}"
  notify: Reload apache

- name: Configure the security settings
  become: true
  ansible.builtin.lineinfile:
    dest: "/etc/apache2/conf-available/security.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  loop: "{{ apache_security_config }}"
  notify: Reload apache

- name: Configure the ssl settings
  become: true
  ansible.builtin.lineinfile:
    dest: "/etc/apache2/mods-available/ssl.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  loop: "{{ apache_ssl_config }}"
  notify: Reload apache

- name: Configure the hostname settings
  become: true
  ansible.builtin.lineinfile:
    dest: "/etc/apache2/conf-available/hostname.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    create: yes
    mode: "0644"
  loop: "{{ apache_hostname_config }}"
  notify: Reload apache

- name: Enable the hostname configs
  become: true
  ansible.builtin.file:
    src: "/etc/apache2/conf-available/hostname.conf"
    dest: "/etc/apache2/conf-enabled/hostname.conf"
    state: link
  notify: Reload apache

- name: Change the listen ports to 0.0.0.0
  become: true
  ansible.builtin.replace:
    path: "/etc/apache2/ports.conf"
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  loop: "{{ apache_listen_ports_config }}"
  notify: Reload apache

- name: Enable apache2 and start it
  become: true
  ansible.builtin.service:
    name: apache2
    state: started
    enabled: yes
