---

- name: install required packages
  become: yes
  apt:
    name: "{{ apache_required_packages }}"
    state: present

- name: install apache2
  become: yes
  apt:
    name: "apache2"
    state: present
