---

- name: Install required packages
  become: true
  ansible.builtin.apt:
    name: "{{ apache_required_packages }}"
    state: present

- name: Install apache2
  become: true
  ansible.builtin.apt:
    name: "apache2"
    state: present
