---

- name: add the dns resolver ip to resolv.conf.d
  become: yes
  lineinfile:
    path: "/etc/resolvconf/resolv.conf.d/tail"
    regexp: "^nameserver {{ resolvconf_dns_resolver_ip }}"
    line: "nameserver {{ resolvconf_dns_resolver_ip }}"
    state: present
