---

- name: Add the dns resolver ip to resolv.conf.d
  become: true
  ansible.builtin.lineinfile:
    path: "/etc/resolvconf/resolv.conf.d/head"
    regexp: "^nameserver (.*)"
    line: "nameserver {{ resolvconf_dns_resolver_ip }}"
    state: present
  notify: Run resolvconf update
