---

- name: add the dns resolver ip to resolv.conf.d
  become: true
  lineinfile:
    path: "/etc/resolvconf/resolv.conf.d/head"
    regexp: "^nameserver (.*)"
    line: "nameserver {{ resolvconf_dns_resolver_ip }}"
    state: present
  notify: resolvconf_update
