---

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pycqa/flake8
    rev: '7.3.0'
    hooks:
      - id: flake8
  - repo: https://github.com/adrienverge/yamllint
    rev: 'v1.37.1'
    hooks:
      - id: yamllint
  - repo: https://github.com/ansible/ansible-lint
    rev: 'v25.6.1'
    hooks:
      - id: ansible-lint
        additional_dependencies:
          - ansible
