[tool.poetry]
name = "homelab-playbooks"
version = "0.1.0"
description = ""
authors = ["Bakie <bakelants.developer@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
ansible = "~2.9.0"
mitogen = "^0.2.9"
"github3.py" = "^1.3.0"

[tool.poetry.dev-dependencies]
molecule = "^3.0.3"
ansible-lint = "^4.2.0"
flake8 = "^3.7.9"
docker-py = "^1.10.6"
testinfra = "^5.0.0"
pytest = "^5.4.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
