groups:
  - name: Downloaders
    rules:
      - alert: NfsKernlerServerDown
        expr: node_nfsd_server_threads == 0
        labels:
          severity: "critical"
        annotations:
          summary: "Total number of NFSd kernel threads is 0 (instance {{ $labels.instance }})"
          description: "NFSd kernel threads is 0 \n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
