---

node_exporter_user: "node_exporter"
node_exporter_group: "node_exporter"
node_exporter_home: "/opt/node_exporter"
node_exporter_config_path: "/etc/node_exporter/config"
node_exporter_version: 1.0.1
node_exporter_download_url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
node_exporter_web_listen_port: "9100"
node_exporter_web_listen_address: "0.0.0.0:{{ node_exporter_web_listen_port }}"
node_exporter_enabled_collectors:
  - arp
  - bonding
  - cpu
  - diskstats
node_exporter_disabled_collectors: []
