---

blackbox_exporter_user: "blackbox_exporter"
blackbox_exporter_group: "blackbox_exporter"
blackbox_exporter_home: "/opt/blackbox_exporter"
blackbox_exporter_config_path: "/etc/blackbox_exporter"
blackbox_exporter_version: 0.17.0
blackbox_exporter_download_url: "https://github.com/prometheus/blackbox_exporter/releases/download/v{{ blackbox_exporter_version }}/blackbox_exporter-{{ blackbox_exporter_version }}.linux-amd64.tar.gz"
blackbox_exporter_web_listen_port: "9101"
blackbox_exporter_web_listen_address: "0.0.0.0:{{ blackbox_exporter_web_listen_port }}"
blackbox_exporter_cli_flags: {}
blackbox_exporter_configuration_modules:
  http_2xx:
    prober: http
    timeout: 5s
    http:
      method: GET
      valid_status_codes: [] # Defaults to 2xx
      preferred_ip_protocol: "ip4"
