---

- name: reload transmission
  become: yes
  service:
    name: transmission-daemon
    state: reloaded

- name: restart transmission
  become: yes
  service:
    name: transmission-daemon
    state: restarted
