---

- name: Reload transmission
  become: true
  ansible.builtin.service:
    name: transmission-daemon
    state: reloaded

- name: Restart transmission
  become: true
  ansible.builtin.service:
    name: transmission-daemon
    state: restarted
