---

prometheus_alertmanager_download_url: "https://github.com/prometheus/alertmanager/releases/download/v{{ prometheus_alertmanager_version }}/alertmanager-{{ prometheus_alertmanager_version }}.linux-{{ deb_architecture.stdout }}.tar.gz"
prometheus_alertmanager_gotify_bridge_download_url: "https://github.com/DRuggeri/alertmanager_gotify_bridge/releases/download/{{ prometheus_alertmanager_gotify_bridge_version }}/alertmanager_gotify_bridge-{{ prometheus_alertmanager_gotify_bridge_version }}-linux-{{ deb_architecture.stdout }}"
