---

- name: Converge
  hosts: all
  vars:
    pihole_custom_dns_entries:
      - ip: 10.1.1.100
        url: pihole.custom.dns
      - ip: 10.1.1.83
        url: pihole_test.custom.dns

  roles:
    - role: pihole
