---

grafana_required_packages: [ "apt-transport-https", "adduser", "libfontconfig", "gnupg2" ]
grafana_apt_key_url: "https://packages.grafana.com/gpg.key"
grafana_apt_repo_url: "deb https://packages.grafana.com/oss/deb stable main"
