{
 "title": "Utilities",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  { "title": "Today", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Todays power usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ha_sensor_energy_kwh{domain=\"sensor\",entity=~\"sensor.energy_consumed_tariff.+\"}[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Todays gas usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(ha_sensor_gas_mu0xb3{domain=\"sensor\",entity=\"sensor.gas_consumed\"}[24h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Todays water usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(ha_sensor_water_mu0xb3{domain=\"sensor\",entity=\"sensor.water_consumed\"}[24h])*1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Power usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ha_sensor_power_kw{domain=\"sensor\",entity=\"sensor.power_consumed\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Quarterly Demand",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ha_sensor_power_kw{domain=\"sensor\",entity=\"sensor.current_average_quarterly_demand\"}",
     "legendFormat": "{{friendly_name}}"
    },
    {
     "expr": "ha_sensor_power_kw{domain=\"sensor\",entity=\"sensor.month_maximum_quarterly_demand\"}",
     "legendFormat": "{{friendly_name}}"
    },
    {
     "expr": "ha_sensor_power_kw{domain=\"sensor\",entity=\"sensor.13_month_maximum_quarterly_demand\"}",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Current power usage per phase",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "expr": "ha_sensor_power_kw{entity=~\"sensor.power_consumed.*\"}",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Gas usage (m³)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "targets": [
    {
     "expr": "increase(ha_sensor_gas_mu0xb3{domain=\"sensor\",entity=\"sensor.gas_consumed\"}[1m])",
     "legendFormat": "per minute"
    },
    {
     "expr": "increase(ha_sensor_gas_mu0xb3{domain=\"sensor\",entity=\"sensor.gas_consumed\"}[1h])",
     "legendFormat": "per hour"
    }
   ]
  },
  {
   "title": "Water usage (L)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "targets": [
    {
     "expr": "increase(ha_sensor_water_mu0xb3{domain=\"sensor\",entity=\"sensor.water_consumed\"}[1m])*1000",
     "legendFormat": "per minute"
    },
    {
     "expr": "increase(ha_sensor_water_mu0xb3{domain=\"sensor\",entity=\"sensor.water_consumed\"}[1h])*1000",
     "legendFormat": "per hour"
    }
   ]
  },
  { "title": "Weekly", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Power",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "sum(increase(ha_sensor_energy_kwh{domain=\"sensor\",entity=~\"sensor.energy_consumed_tariff.+\"}[1d] offset -1d))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Gas",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "targets": [
    {
     "expr": "sum(increase(ha_sensor_gas_mu0xb3{domain=\"sensor\",entity=\"sensor.gas_consumed\"}[1d] offset -1d))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Water",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "targets": [
    {
     "expr": "sum(increase(ha_sensor_water_mu0xb3{domain=\"sensor\",entity=\"sensor.water_consumed\"}[1d] offset -1d))*1000",
     "legendFormat": "{{label_name}}"
    }
   ]
  }
 ]
}