---

- name: create service file
  become: yes
  template:
    src: blackbox_exporter.service.j2
    dest: /lib/systemd/system/blackbox_exporter.service
    owner: root
    group: root
    mode: 0644
  notify: restart blackbox_exporter

- name: enable and start blackbox_exporter
  become: yes
  service:
    daemon_reload: yes
    name: blackbox_exporter
    state: started
    enabled: yes
