---

- name: Set config variables in the settings.json file
  become: true
  ansible.builtin.lineinfile:
    dest: "{{ transmission_settings_file_path }}"
    insertafter: "^    {{ item.option }}: "
    regexp: "^    {{ item.option }}: (?! {{ item.value }})"
    line: "    {{ item.option }}: {{ item.value }},"
    state: present
  loop: "{{ transmission_settings }}"
  notify: Reload transmission
