---

- name: install transmission
  become: yes
  apt:
    name: [ "transmission-cli", "transmission-common", "transmission-daemon" ]
    state: present
    install_recommends: no

- name: set correct user in systemd file
  become: yes
  lineinfile:
    dest: "/lib/systemd/system/transmission-daemon.service"
    regexp: "^User="
    line: "User={{ transmission_user }}"
    state: present

- name: start transmission
  become: yes
  systemd:
    name: transmission-daemon
    state: started
    enabled: yes
    daemon-reload: yes
