---

- name: Install transmission
  become: true
  ansible.builtin.apt:
    name: [ "transmission-cli", "transmission-common", "transmission-daemon" ]
    state: present
    install_recommends: no

- name: Set correct user in systemd file
  become: true
  ansible.builtin.lineinfile:
    dest: "/lib/systemd/system/transmission-daemon.service"
    regexp: "^User="
    line: "User={{ transmission_user }}"
    state: present
  notify: Restart transmission

- name: Start transmission
  become: true
  ansible.builtin.systemd:
    name: transmission-daemon
    state: started
    enabled: yes
    daemon-reload: yes

# When installing for the first time the settings.json files is not yet present
# When restarting transmission the settings.json file gets created
- name: Flush the handlers
  ansible.builtin.meta: flush_handlers
