---

- name: Remove default debian-transmission user
  become: true
  ansible.builtin.user:
    name: "debian-transmission"
    state: absent

- name: Remove default debian-transmission group
  become: true
  ansible.builtin.group:
    name: "debian-transmission"
    state: absent

- name: Remove the /etc/transmission-daemon dir
  become: true
  ansible.builtin.file:
    path: "/etc/transmission-daemon"
    state: absent
