---

- name: Install required packages
  become: true
  ansible.builtin.apt:
    name: "procps"
    state: present

- name: Add transmission group
  become: true
  ansible.builtin.group:
    name: "{{ transmission_group }}"
    state: present

- name: Create transmission user
  become: true
  ansible.builtin.user:
    name: "{{ transmission_user }}"
    shell: "/usr/sbin/nologin"
    home: "{{ transmission_install_path }}"
    system: yes
    group: "{{ transmission_group }}"
    state: present

- name: Create necessary dirs
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ transmission_user }}"
    group: "{{ transmission_group }}"
    mode: "0755"
  loop: "{{ transmission_required_paths }}"
