---

- name: add transmission group
  become: yes
  group:
    name: "{{ transmission_group }}"
    state: present

- name: create transmission user
  become: yes
  user:
    name: "{{ transmission_user }}"
    home: "{{ transmission_user_home }}"
    system: yes
    group: "{{ transmission_group }}"
    state: present

- name: create necessary dirs
  become: yes
  file:
    path: "{{ transmission_user_home }}/{{ item }}"
    state: directory
    owner: "{{ transmission_user }}"
    group: "{{ transmission_group }}"
  loop:
    - completed
    - incomplete
    - torrents
    - watchdir
