---

- name: add transmission group
  become: yes
  group:
    name: "{{ transmission_group }}"
    state: present

- name: create transmission user
  become: yes
  user:
    name: "{{ transmission_user }}"
    shell: "/usr/sbin/nologin"
    home: "{{ transmission_install_path }}"
    system: yes
    group: "{{ transmission_group }}"
    state: present

- name: create necessary dirs
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ transmission_user }}"
    group: "{{ transmission_group }}"
    mode: 0755
  loop: "{{ transmission_required_paths }}"
