---

- name: configure apache vhost {{ vhost.name }}
  become: true
  template:
    src: "vhost_{{ vhost.template }}.conf.j2"
    dest: "/etc/apache2/sites-available/{{ vhost.name }}.conf"
    mode: 0644
  notify: reload apache

- name: link apache vhost {{ vhost.name }}
  become: true
  file:
    src: "/etc/apache2/sites-available/{{ vhost.name }}.conf"
    dest: "/etc/apache2/sites-enabled/{{ vhost.name }}.conf"
    state: link
  notify: reload apache
