---

- name: Configure apache vhost
  become: true
  ansible.builtin.template:
    src: "vhost_{{ vhost.template }}.conf.j2"
    dest: "/etc/apache2/sites-available/{{ vhost.name }}.conf"
    mode: "0644"
  notify: Reload apache

- name: Link apache vhost
  become: true
  ansible.builtin.file:
    src: "/etc/apache2/sites-available/{{ vhost.name }}.conf"
    dest: "/etc/apache2/sites-enabled/{{ vhost.name }}.conf"
    state: link
  notify: Reload apache
