---

- include_tasks: assert.yml

- name: Create necessary directories
  become: yes
  file:
    path: "{{ item }}"
    access_time: preserve
    state: directory
    mode: 0755
  loop:
    - "/etc/apache2"
    - "/etc/apache2/sites-available"
    - "/etc/apache2/sites-enabled"

- include_tasks: configure_vhost.yml
  loop: "{{ available_apache_vhosts }}"
  loop_control:
    loop_var: apache_vhost_var
  when: apache_vhost_var in required_apache_vhosts
