---

- name: Converge
  hosts: all
  vars:
    prometheus_metrics_job_targets:
      - 10.1.1.1
    prometheus_metrics_job_relabel_configs:
      - source_labels: "[__custom_source_label__]"
        regex: custom\\.regex\\.test(.*)
        replacement: custom_replacement
        target_label: custom_target_label
    prometheus_blackbox_exporter_targets:
      - url: "blackbox_green.com"
        instance: "green"
        job: "blackbox_green"
      - url: "blackbox_blue.com"
        instance: "blue"
        job: "blackbox_blue"

  roles:
    - role: prometheus
