---

- name: Converge
  hosts: all
  vars:
    prometheus_blackbox_targets:
      - url: "blackbox_green.com"
        job: "blackbox_green"
      - url: "blackbox_blue.com"
        job: "blackbox_blue"
    prometheus_alertmanagers: ["localhost:9093"]

  roles:
    - role: prometheus
