---

- name: create node_exporter config directory
  become: yes
  file:
    path: "{{ node_exporter_config_path }}"
    state: directory
    owner: "{{ node_exporter_user }}"
    group: "{{ node_exporter_group }}"
    mode: 0775

- name: configure node_exporter config.yml
  become: yes
  become_user: "{{ node_exporter_user }}"
  template:
    src: "config.yml.j2"
    dest: "{{ node_exporter_config_path }}/config.yml"
    group: "{{ node_exporter_group }}"
    mode: 0640
  notify: restart node_exporter
