---

- name: stat node_exporter binary
  stat:
    path: "{{ node_exporter_home }}/node_exporter"
  register: node_exporter_binary

- name: stat current node_exporter version
  shell: |
    set -o pipefail
    ./node_exporter --version 2>&1 | head -1 | awk '{print $3}'
  args:
    chdir: "{{ node_exporter_home }}"
    executable: "/bin/bash"
  when: node_exporter_binary.stat.exists
  register: node_exporter_current_version
  changed_when: false

- name: install node_exporter block
  block:
    - name: unarchive node_exporter
      become: yes
      become_user: "{{ node_exporter_user }}"
      unarchive:
        src: "{{ node_exporter_download_url }}"
        dest: "/tmp"
        remote_src: yes

    - name: copy node_exporter
      become: yes
      become_user: "{{ node_exporter_user }}"
      copy:
        src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
        dest: "{{ node_exporter_home }}/node_exporter"
        remote_src: yes
        mode: 0755
        owner: "{{ node_exporter_user }}"
        group: "{{ node_exporter_group }}"
      notify:
        - restart node_exporter

    - name: remove downloaded files
      become: yes
      file:
        path: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64"
        state: absent
  when: not node_exporter_binary.stat.exists or node_exporter_current_version.stdout != node_exporter_version
