---

- name: create service file
  become: yes
  template:
    src: node_exporter.service.j2
    dest: /lib/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: 0644
  notify: restart node_exporter

- name: enable and start node_exporter
  become: yes
  service:
    daemon_reload: yes
    name: node_exporter
    state: started
    enabled: yes
