---

- name: add node_exporter group
  become: yes
  group:
    name: "{{ node_exporter_group }}"
    system: yes
    state: present

- name: create node_exporter user
  become: yes
  user:
    name: "{{ node_exporter_user }}"
    home: "{{ node_exporter_home }}"
    create_home: no
    system: yes
    group: "{{ node_exporter_group }}"
    state: present

- name: create node_exporter home
  become: yes
  file:
    path: "{{ node_exporter_home }}"
    state: directory
    owner: "{{ node_exporter_user }}"
    group: "{{ node_exporter_group }}"
    mode: 0755
