---

- name: add prometheus_node_exporter group
  become: yes
  group:
    name: "{{ prometheus_node_exporter_group }}"
    system: yes
    state: present

- name: create prometheus_node_exporter user
  become: yes
  user:
    name: "{{ prometheus_node_exporter_user }}"
    home: "{{ prometheus_node_exporter_home }}"
    create_home: no
    system: yes
    group: "{{ prometheus_node_exporter_group }}"
    state: present

- name: create prometheus_node_exporter home
  become: yes
  file:
    path: "{{ prometheus_node_exporter_home }}"
    state: directory
    owner: "{{ prometheus_node_exporter_user }}"
    group: "{{ prometheus_node_exporter_group }}"
    mode: 0755
