---

- name: Create prometheus_node_exporter directories
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ prometheus_node_exporter_user }}"
    group: "{{ prometheus_node_exporter_group }}"
    mode: "0755"
  loop:
    - "{{ prometheus_node_exporter_config_path }}"
    - "{{ prometheus_node_exporter_textfile_scripts_path }}"
    - "{{ prometheus_node_exporter_textfile_scripts_output_path }}"

- name: Copy the prometheus_node_exporter config file
  become: true
  ansible.builtin.template:
    src: config.yml.j2
    dest: "{{ prometheus_node_exporter_config_path }}/config.yml"
    owner: "{{ prometheus_node_exporter_user }}"
    group: "{{ prometheus_node_exporter_group }}"
    mode: "0644"
  notify: Restart prometheus_node_exporter
