---

- name: get the deb architecture
  command: dpkg --print-architecture
  register: deb_architecture
  changed_when: false

- name: create the prometheus_node_exporter_install_path base dir
  become: yes
  file:
    path: "{{ prometheus_node_exporter_install_path | regex_replace('/$', '') | dirname }}"
    state: directory
    mode: 0755

- name: download and unarchive prometheus_node_exporter
  become: yes
  unarchive:
    src: "{{ prometheus_node_exporter_download_url }}"
    dest: /tmp
    remote_src: yes

- name: Remove currently installed prometheus_node_exporter version
  become: yes
  file:
    path: "{{ prometheus_node_exporter_install_path }}"
    state: absent

- name: rename prometheus_node_exporter directory
  become: yes
  command: "mv /tmp/node_exporter-{{ prometheus_node_exporter_version }}.linux-{{ deb_architecture.stdout }} {{ prometheus_node_exporter_install_path }}"
  args:
    creates: "{{ prometheus_node_exporter_install_path }}"
  notify: restart prometheus_node_exporter

- name: set permissions on prometheus_node_exporter_install_path
  become: yes
  file:
    path: "{{ prometheus_node_exporter_install_path }}"
    recurse: yes
    mode: 0755
    owner: "{{ prometheus_node_exporter_user }}"
    group: "{{ prometheus_node_exporter_group }}"
  notify: restart prometheus_node_exporter
