---

- name: stat prometheus_node_exporter binary
  stat:
    path: "{{ prometheus_node_exporter_home }}/node_exporter"
  register: prometheus_node_exporter_binary

- name: stat current prometheus_node_exporter version
  shell: "./node_exporter --version 2>&1 | head -1 | awk '{print $3}'"
  args:
    chdir: "{{ prometheus_node_exporter_home }}"
  when: prometheus_node_exporter_binary.stat.exists
  register: prometheus_node_exporter_current_version
  changed_when: false

- name: install prometheus_node_exporter block
  block:
    - name: unarchive prometheus_node_exporter
      become: yes
      become_user: "{{ prometheus_node_exporter_user }}"
      unarchive:
        src: "https://github.com/prometheus/node_exporter/releases/download/v{{ prometheus_node_exporter_version }}/node_exporter-{{ prometheus_node_exporter_version }}.linux-amd64.tar.gz"
        dest: "/tmp"
        remote_src: yes

    - name: copy prometheus_node_exporter
      become: yes
      become_user: "{{ prometheus_node_exporter_user }}"
      copy:
        src: "/tmp/node_exporter-{{ prometheus_node_exporter_version }}.linux-amd64/node_exporter"
        dest: "{{ prometheus_node_exporter_home }}/node_exporter"
        remote_src: yes
        mode: 0755
        owner: "{{ prometheus_node_exporter_user }}"
        group: "{{ prometheus_node_exporter_group }}"
      notify:
        - restart prometheus_node_exporter

    - name: remove downloaded files
      become: yes
      file:
        path: "/tmp/node_exporter-{{ prometheus_node_exporter_version }}.linux-amd64"
        state: absent
  when: not prometheus_node_exporter_binary.stat.exists or prometheus_node_exporter_current_version.stdout != prometheus_node_exporter_version
