---

- name: Create service file
  become: true
  ansible.builtin.template:
    src: prometheus_node_exporter.service.j2
    dest: /etc/systemd/system/prometheus_node_exporter.service
    owner: root
    group: root
    mode: "0644"
  notify: Restart prometheus_node_exporter

- name: Enable and start prometheus_node_exporter
  become: true
  ansible.builtin.service:
    daemon_reload: yes
    name: prometheus_node_exporter
    state: started
    enabled: yes
