---

- name: create service file
  become: true
  template:
    src: prometheus_node_exporter.service.j2
    dest: /etc/systemd/system/prometheus_node_exporter.service
    owner: root
    group: root
    mode: 0644
  notify: restart prometheus_node_exporter

- name: enable and start prometheus_node_exporter
  become: true
  service:
    daemon_reload: yes
    name: prometheus_node_exporter
    state: started
    enabled: yes
