---

- name: Create prometheus_node_exporter group
  become: true
  ansible.builtin.group:
    name: "{{ prometheus_node_exporter_group }}"
    system: yes
    state: present

- name: Create prometheus_node_exporter user
  become: true
  ansible.builtin.user:
    name: "{{ prometheus_node_exporter_user }}"
    shell: "/usr/sbin/nologin"
    system: yes
    group: "{{ prometheus_node_exporter_group }}"
    create_home: no
    home: "{{ prometheus_node_exporter_install_path }}"

- name: Create prometheus base paths
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ prometheus_node_exporter_base_path }}"
    - "{{ prometheus_node_exporter_base_config_path }}"
