---

- name: copy the script {{ textfile_script.script_name }}
  become: yes
  copy:
    src: "{{ textfile_script.script_name }}"
    dest: "{{ prometheus_node_exporter_textfile_scripts_path }}"
    owner: "{{ prometheus_node_exporter_user }}"
    group: "{{ prometheus_node_exporter_group }}"
    mode: 0755

- name: add the cronjob {{ textfile_script.cronjob.name }} to the root user
  become: yes
  cron:
    name: "{{ textfile_script.cronjob.name }}"
    minute: "{{ textfile_script.cronjob.minute|d('*') }}"
    hour: "{{ textfile_script.cronjob.hour|d('*') }}"
    job: "{{ textfile_script.cronjob.job }}"
