---

- name: Stat prometheus_node_exporter binary
  ansible.builtin.stat:
    path: "{{ prometheus_node_exporter_install_path }}/node_exporter"
  register: prometheus_node_exporter_binary

- name: Get current prometheus_node_exporter version
  ansible.builtin.shell: |
    set -o pipefail
    ./node_exporter --version 2>&1 | head -1 | awk '{print $3}'
  args:
    chdir: "{{ prometheus_node_exporter_install_path }}"
    executable: /bin/bash
  when: prometheus_node_exporter_binary.stat.exists
  changed_when: false
  register: prometheus_node_exporter_current_version

- name: Set fact to install prometheus_node_exporter
  ansible.builtin.set_fact:
    prometheus_node_exporter_install: "{{ not prometheus_node_exporter_binary.stat.exists or prometheus_node_exporter_current_version.stdout != prometheus_node_exporter_version }}"
