---


- name: Configure the settings
  become: true
  ansible.builtin.lineinfile:
    dest: "{{ vikunja_config_file_path }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  loop: "{{ vikunja_config }}"
  notify: Restart vikunja
