---


- name: configure the settings
  become: true
  lineinfile:
    dest: "{{ vikunja_config_file_path }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  loop: "{{ vikunja_config }}"
  notify: restart vikunja
