---

- name: Install vikunja deb file
  become: true
  ansible.builtin.apt:
    deb: "{{ vikunja_download_url }}"
    state: "present"

- name: Set owner/group on vikunja install path
  become: true
  ansible.builtin.file:
    path: "{{ vikunja_install_path }}"
    owner: "{{ vikunja_user }}"
    group: "{{ vikunja_group }}"
    recurse: true
