---

- name: Createe service file
  become: true
  ansible.builtin.template:
    src: vikunja.service.j2
    dest: /etc/systemd/system/vikunja.service
    owner: root
    group: root
    mode: "0644"
  notify: Restart vikunja

- name: Enable and start vikunja
  become: true
  ansible.builtin.service:
    daemon_reload: yes
    name: vikunja
    state: started
    enabled: yes
