---

- name: Install required packages
  become: true
  ansible.builtin.apt:
    name: "sqlite3"
    state: present

- name: Createe vikunja group
  become: true
  ansible.builtin.group:
    name: "{{ vikunja_group }}"
    system: yes
    state: present

- name: Createe vikunja user
  become: true
  ansible.builtin.user:
    name: "{{ vikunja_user }}"
    shell: "/usr/sbin/nologin"
    system: yes
    group: "{{ vikunja_group }}"
    create_home: no
    home: "{{ vikunja_install_path }}"
