---

- name: work around permission issue
  command: git config --global --add safe.directory {{ medusa_install_path }}
  changed_when: no
  tags: skip_ansible_lint

- name: clone the medusa gitrepo
  become: yes
  git:
    repo: "{{ medusa_repo_url }}"
    dest: "{{ medusa_install_path }}"
    version: "{{ medusa_version }}"
    depth: 1
  notify: set owner/group on medusa install path
