---

- name: Work around permission issue
  become: true
  ansible.builtin.command: git config --global --add safe.directory {{ medusa_install_path }}
  changed_when: no
  tags: skip_ansible_lint

- name: Clone the medusa gitrepo
  become: true
  ansible.builtin.git:
    repo: "{{ medusa_repo_url }}"
    dest: "{{ medusa_install_path }}"
    version: "{{ medusa_version }}"
    depth: 1
  notify: Set owner/group on medusa install path
