---

- name: Template the service file
  become: true
  ansible.builtin.template:
    src: "medusa.service.j2"
    dest: "/etc/systemd/system/medusa.service"
    mode: "0644"
  notify: Restart medusa

- name: Start and enable medusa
  become: true
  ansible.builtin.service:
    name: medusa
    state: started
    enabled: yes
    daemon_reload: yes
