---

- name: template the service file
  become: yes
  template:
    src: "medusa.service.j2"
    dest: "/etc/systemd/system/medusa.service"
    mode: 0644
  notify: restart medusa

- name: start and enable medusa
  become: yes
  service:
    name: medusa
    state: started
    enabled: yes
    daemon_reload: yes
