---

- name: install required packages
  become: yes
  apt:
    name: "{{ medusa_required_packages }}"
    state: present

- name: add medusa group
  become: yes
  group:
    name: "{{ medusa_group }}"
    state: present

- name: create medusa user
  become: yes
  user:
    name: "{{ medusa_user }}"
    comment: "medusa"
    home: "{{ medusa_install_path }}"
    create_home: no # We create the homedir separately so it remains empty and the git clone doesn't complain
    system: yes
    group: "{{ medusa_group }}"
    state: present

- name: ensure {{ medusa_install_path }} dir exists
  become: yes
  file:
    path: "{{ medusa_install_path }}"
    owner: "{{ medusa_user }}"
    group: "{{ medusa_group }}"
    state: directory
