---

- name: Install required packages
  become: true
  ansible.builtin.apt:
    name: "{{ medusa_required_packages }}"
    state: present

- name: Add medusa group
  become: true
  ansible.builtin.group:
    name: "{{ medusa_group }}"
    state: present

- name: Create medusa user
  become: true
  ansible.builtin.user:
    name: "{{ medusa_user }}"
    comment: "medusa"
    home: "{{ medusa_install_path }}"
    create_home: no  # We create the homedir separately so it remains empty and the git clone doesn't complain
    system: yes
    group: "{{ medusa_group }}"
    state: present

- name: Ensure the medusa install path exists
  become: true
  ansible.builtin.file:
    path: "{{ medusa_install_path }}"
    owner: "{{ medusa_user }}"
    group: "{{ medusa_group }}"
    state: directory
    mode: "0755"
