---

- name: install necessary packages
  become: yes
  apt:
    name: [ "git-core", "python3", "mediainfo", "unrar-free", "openssl", "libssl-dev" ]
    state: present

- name: add medusa group
  become: yes
  group:
    name: "{{ medusa_group }}"
    state: present

- name: create medusa user
  become: yes
  user:
    name: "{{ medusa_user }}"
    comment: "medusa"
    home: "{{ medusa_user_home }}"
    create_home: no # We create the homedir separately so it remains empty and the git clone doesn't complain
    system: yes
    group: "{{ medusa_group }}"
    state: present

- name: ensure {{ medusa_user_home }} dir exists
  become: yes
  file:
    path: "{{ medusa_user_home }}"
    owner: "{{ medusa_user }}"
    group: "{{ medusa_group }}"
    state: directory
