---

top_lvl_domain: "home"
grafana_url: "grafana.{{ top_lvl_domain }}"
medusa_url: "medusa.{{ top_lvl_domain }}"
prometheus_url: "prometheus.{{ top_lvl_domain }}"
prometheus_alertmanager_web_external_url: "prometheus-alertmanager.{{ top_lvl_domain }}"
sabnzbd_url: "sabnzbd.{{ top_lvl_domain }}"
transmission_url: "transmission.{{ top_lvl_domain }}"

# resolvconf role
resolvconf_dns_resolver_ip: 10.1.1.99
