---

gotify_url: "gotify.{{ top_lvl_domain }}"
grafana_url: "grafana.{{ top_lvl_domain }}"
medusa_url: "medusa.{{ top_lvl_domain }}"
miniflux_url: "miniflux.{{ top_lvl_domain }}"
prometheus_url: "prometheus.{{ top_lvl_domain }}"
prometheus_alertmanager_web_external_url: "prometheus-alertmanager.{{ top_lvl_domain }}"
sabnzbd_url: "sabnzbd.{{ top_lvl_domain }}"
transmission_url: "transmission.{{ top_lvl_domain }}"
vikunja_url: "vikunja.{{ top_lvl_domain }}"
