---

top_lvl_domain: "homelab.net"
grafana_url: "grafana.{{ top_lvl_domain }}"
medusa_url: "medusa.{{ top_lvl_domain }}"
prometheus_url: "prometheus.{{ top_lvl_domain }}"
sabnzbd_url: "sabnzbd.{{ top_lvl_domain }}"
transmission_url: "transmission.{{ top_lvl_domain }}"
