---

- name: Create prometheus_blackbox_exporter configuration directories
  become: true
  ansible.builtin.file:
    path: "{{ prometheus_blackbox_exporter_config_path }}"
    state: directory
    owner: "{{ prometheus_blackbox_exporter_user }}"
    group: "{{ prometheus_blackbox_exporter_group }}"
    mode: "0755"

- name: Template the prometheus_blackbox_exporter config file
  become: true
  ansible.builtin.template:
    src: config.yml.j2
    dest: "{{ prometheus_blackbox_exporter_config_path }}/config.yml"
    owner: "{{ prometheus_blackbox_exporter_user }}"
    group: "{{ prometheus_blackbox_exporter_group }}"
    mode: "0644"
  notify: Restart prometheus_blackbox_exporter

- name: Ensure blackbox exporter binary has cap_net_raw capability
  become: true
  community.general.capabilities:
    path: "{{ prometheus_blackbox_exporter_install_path }}/blackbox_exporter"
    capability: cap_net_raw=ep
    state: present
