---

- name: Get the deb architecture
  ansible.builtin.command: dpkg --print-architecture
  register: deb_architecture
  changed_when: false

- name: Create the prometheus_blackbox_exporter_install_path base dir
  become: true
  ansible.builtin.file:
    path: "{{ prometheus_blackbox_exporter_install_path | regex_replace('/$', '') | dirname }}"
    state: directory
    mode: "0755"

- name: Download and unarchive prometheus_blackbox_exporter
  become: true
  ansible.builtin.unarchive:
    src: "{{ prometheus_blackbox_exporter_download_url }}"
    dest: /tmp
    remote_src: yes

- name: Remove currently installed prometheus_blackbox_exporter version
  become: true
  ansible.builtin.file:
    path: "{{ prometheus_blackbox_exporter_install_path }}"
    state: absent

- name: Rename prometheus_blackbox_exporter directory
  become: true
  ansible.builtin.command: "mv /tmp/blackbox_exporter-{{ prometheus_blackbox_exporter_version }}.linux-{{ deb_architecture.stdout }} {{ prometheus_blackbox_exporter_install_path }}"
  args:
    creates: "{{ prometheus_blackbox_exporter_install_path }}"
  notify: Restart prometheus_blackbox_exporter

- name: Set permissions on prometheus_blackbox_exporter_install_path
  become: true
  ansible.builtin.file:
    path: "{{ prometheus_blackbox_exporter_install_path }}"
    recurse: yes
    mode: "0755"
    owner: "{{ prometheus_blackbox_exporter_user }}"
    group: "{{ prometheus_blackbox_exporter_group }}"
  notify: Restart prometheus_blackbox_exporter
