---

- include_tasks: setup.yml
- include_tasks: version_check.yml
- include_tasks: install.yml
  when: install_prometheus_blackbox_exporter
- include_tasks: configure.yml
- include_tasks: service.yml
