---

- name: create service file
  become: yes
  template:
    src: prometheus_blackbox_exporter.service.j2
    dest: /etc/systemd/system/prometheus_blackbox_exporter.service
    owner: root
    group: root
    mode: 0644
  notify: restart prometheus_blackbox_exporter

- name: enable and start prometheus_blackbox_exporter
  become: yes
  service:
    daemon_reload: yes
    name: prometheus_blackbox_exporter
    state: started
    enabled: yes
