---

- name: create prometheus_blackbox_exporter group
  become: yes
  group:
    name: "{{ prometheus_blackbox_exporter_group }}"
    system: yes
    state: present

- name: create prometheus_blackbox_exporter user
  become: yes
  user:
    name: "{{ prometheus_blackbox_exporter_user }}"
    shell: "/usr/sbin/nologin"
    system: yes
    group: "{{ prometheus_blackbox_exporter_group }}"
    create_home: no
    home: "{{ prometheus_blackbox_exporter_install_path }}"

- name: create prometheus base paths
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  loop:
    - "{{ prometheus_blackbox_exporter_base_path }}"
    - "{{ prometheus_blackbox_exporter_base_config_path }}"
