---

- name: stat prometheus_blackbox_exporter binary
  stat:
    path: "{{ prometheus_blackbox_exporter_install_path }}/blackbox_exporter"
  register: prometheus_blackbox_exporter_binary

- name: get current prometheus_blackbox_exporter version
  shell: |
    set -o pipefail
    ./blackbox_exporter --config.file=config,yml --version 2>&1 | head -1 | awk '{print $3}'
  args:
    chdir: "{{ prometheus_blackbox_exporter_install_path }}"
    executable: /bin/bash
  when: prometheus_blackbox_exporter_binary.stat.exists
  changed_when: false
  register: prometheus_blackbox_exporter_current_version

- name: set fact to install prometheus_blackbox_exporter
  set_fact:
    install_prometheus_blackbox_exporter: "{{ not prometheus_blackbox_exporter_binary.stat.exists or prometheus_blackbox_exporter_current_version.stdout != prometheus_blackbox_exporter_version }}"
