---

- name: set owner/group on medusa install path
  become: true
  file:
    path: "{{ medusa_install_path }}"
    owner: "{{ medusa_user }}"
    group: "{{ medusa_group }}"
    recurse: yes

- name: restart medusa
  become: true
  service:
    name: medusa
    state: restarted
    enabled: yes
