---

- name: Set owner/group on medusa install path
  become: true
  ansible.builtin.file:
    path: "{{ medusa_install_path }}"
    owner: "{{ medusa_user }}"
    group: "{{ medusa_group }}"
    recurse: yes

- name: Restart medusa
  become: true
  ansible.builtin.service:
    name: medusa
    state: restarted
    enabled: yes
