---

- name: Create ssl dir
  become: true
  ansible.builtin.file:
    path: "{{ ssl_cert_config.dir }}"
    state: directory
    owner: root
    group: "{{ ssl_cert_group }}"
    mode: "0650"

- name: Create the key file
  become: true
  ansible.builtin.copy:
    content: "{{ ssl_cert_config.key.content }}"
    dest: "{{ ssl_cert_config.dir }}/{{ ssl_cert_config.key.filename }}"
    owner: root
    group: "{{ ssl_cert_group }}"
    mode: "0640"

- name: Create the crt file
  become: true
  ansible.builtin.copy:
    content: "{{ ssl_cert_config.crt.content }}"
    dest: "{{ ssl_cert_config.dir }}/{{ ssl_cert_config.crt.filename }}"
    owner: root
    group: "{{ ssl_cert_group }}"
    mode: "0640"
