---

- name: change the default settings of sabnzbdplus
  become: yes
  lineinfile:
    path: "/etc/default/sabnzbdplus"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - { regexp: "^USER=", line: "USER={{ sabnzbd_user }}" }
    - { regexp: "^HOST=", line: "HOST={{ sabnzbd_host }}" }
    - { regexp: "^PORT=", line: "PORT={{ sabnzbd_listen_port }}" }
  notify: restart sabnzbd

- name: start and enable sabnzbd
  become: yes
  service:
    name: sabnzbdplus
    state: started
    enabled: yes

# When installing for the first time the sabnzbd.ini.bak takes some time to get the correct contents.
# If we then change the host_whitelist in the task below it gets overwritten once the .bak file is correct.
# When restarting it the sabnzbd.ini.bak gets its content set correctly.
- name: flush the handlers
  meta: flush_handlers

- name: add the sabnzbd_url to host_whitelist
  become: yes
  lineinfile:
    path: "{{ sabnzbd_install_path }}/.sabnzbd/sabnzbd.ini"
    regexp: "^host_whitelist.*"
    line: "host_whitelist = {{ inventory_hostname }}, {{ sabnzbd_url }}"
  notify: restart sabnzbd
