---

- name: Add the debian repositories
  become: true
  ansible.builtin.replace:
    path: "/etc/apt/sources.list.d/debian.sources"
    regexp: '^(Components(?!.* {{ item }}).*)'
    replace: '\1 {{ item }}'
  loop:
    - "contrib"
    - "non-free"
    - "non-free-firmware"

- name: Install required packages
  become: true
  ansible.builtin.apt:
    name: [ "software-properties-common", "unrar", "python3-cheroot" ]
    state: present
    update_cache: yes

- name: Add sabnzbd group
  become: true
  ansible.builtin.group:
    name: "{{ sabnzbd_group }}"
    state: present

- name: Create sabnzbd user
  become: true
  ansible.builtin.user:
    name: "{{ sabnzbd_user }}"
    shell: "/usr/sbin/nologin"
    home: "{{ sabnzbd_install_path }}"
    system: yes
    group: "{{ sabnzbd_group }}"
    state: present

- name: Create nesessary directories
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ sabnzbd_user }}"
    group: "{{ sabnzbd_group }}"
    mode: "0755"
  loop: "{{ sabnzbd_required_paths }}"
