---

- name: install required packages
  become: yes
  apt:
    name: "{{ sabnzbd_required_packages }}"
    state: present

- name: add sabnzbd ppa repository
  become: yes
  apt_repository:
    repo: "{{ sabnzbd_ppa_repository }}"

- name: add sabnzbd-addons ppa repository
  become: yes
  apt_repository:
    repo: "{{ sabnzbd_addons_ppa_repository }}"

- name: add sabnzbd group
  become: yes
  group:
    name: "{{ sabnzbd_group }}"
    state: present

- name: create sabnzbd user
  become: yes
  user:
    name: "{{ sabnzbd_user }}"
    home: "{{ sabnzbd_user_home }}"
    system: yes
    group: "{{ sabnzbd_group }}"
    state: present

- name: create nesessary directories
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ sabnzbd_user }}"
    group: "{{ sabnzbd_group }}"
    mode: 0755
  loop: "{{ sabnzbd_required_paths }}"
