---

- name: add the debian repositories
  become: true
  replace:
    path: "/etc/apt/sources.list.d/debian.sources"
    regexp: '^(Components(?!.* {{ item }}).*)'
    replace: '\1 {{ item }}'
  loop:
    - "contrib"
    - "non-free"
    - "non-free-firmware"

- name: install required packages
  become: true
  apt:
    name: [ "software-properties-common", "unrar", "python3-cheroot" ]
    state: present
    update_cache: yes

- name: add sabnzbd group
  become: true
  group:
    name: "{{ sabnzbd_group }}"
    state: present

- name: create sabnzbd user
  become: true
  user:
    name: "{{ sabnzbd_user }}"
    shell: "/usr/sbin/nologin"
    home: "{{ sabnzbd_install_path }}"
    system: yes
    group: "{{ sabnzbd_group }}"
    state: present

- name: create nesessary directories
  become: true
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ sabnzbd_user }}"
    group: "{{ sabnzbd_group }}"
    mode: 0755
  loop: "{{ sabnzbd_required_paths }}"
