---

- name: add the debian repositories
  become: yes
  replace:
    path: "/etc/apt/sources.list.d/debian.sources"
    regexp: '^(Components(?!.* {{ item }}).*)'
    replace: '\1 {{ item }}'
  loop:
    - "contrib"
    - "non-free"
    - "non-free-firmware"

- name: install required packages
  become: yes
  apt:
    name: "{{ sabnzbd_required_packages }}"
    state: present
    update_cache: yes

#- name: add the contrib repository
#  become: yes
#  replace:
#    path: "/etc/apt/sources.list.d/debian.sources"
#    regexp: '^(Components(?!.* contrib).*)'
#    replace: '\1 contrib'
#
#- name: add the non-free-firmware repository
#  become: yes
#  replace:
#    path: "/etc/apt/sources.list.d/debian.sources"
#    regexp: '^(Components(?!.* non-free-firmware).*)'
#    replace: '\1 non-free-firmware'

#- name: add sabnzbd ppa repository
#  become: yes
#  apt_repository:
#    repo: "{{ sabnzbd_ppa_repository }}"
#
#- name: add sabnzbd-addons ppa repository
#  become: yes
#  apt_repository:
#    repo: "{{ sabnzbd_addons_ppa_repository }}"

- name: add sabnzbd group
  become: yes
  group:
    name: "{{ sabnzbd_group }}"
    state: present

- name: create sabnzbd user
  become: yes
  user:
    name: "{{ sabnzbd_user }}"
    shell: "/usr/sbin/nologin"
    home: "{{ sabnzbd_install_path }}"
    system: yes
    group: "{{ sabnzbd_group }}"
    state: present

- name: create nesessary directories
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ sabnzbd_user }}"
    group: "{{ sabnzbd_group }}"
    mode: 0755
  loop: "{{ sabnzbd_required_paths }}"
