---

- name: template the blackbox alerting
  become: yes
  become_user: "{{ prometheus_user }}"
  template:
    src: "alerting_rules.yml.j2"
    dest: "{{ prometheus_config_path }}/rules/alerting_rules.yml"
    group: "{{ prometheus_group }}"
    mode: 0640
  notify: reload prometheus
