---

- name: create prometheus config directories
  become: yes
  become_user: "{{ prometheus_user }}"
  file:
    path: "{{ prometheus_config_dir }}/{{ item }}"
    state: directory
    group: "{{ prometheus_group }}"
    mode: 0770
  with_items:
    - "rules"
    - "file_sd"
    - "conf.d"

- name: configure prometheus.yml
  become: yes
  become_user: "{{ prometheus_user }}"
  template:
    src: "prometheus.yml.j2"
    dest: "{{ prometheus_config_dir }}/prometheus.yml"
    group: "{{ prometheus_group }}"
    mode: 0640
    validate: "{{ prometheus_home }}/promtool check config %s"
  notify: reload prometheus
