---

- name: create prometheus directories
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: 0755
  loop:
    - "{{ prometheus_data_path }}"
    - "{{ prometheus_rules_config_path }}"
    - "{{ prometheus_file_sd_config_path }}"

- name: configure prometheus.yml
  become: yes
  template:
    src: "prometheus.yml.j2"
    dest: "{{ prometheus_config_path }}/prometheus.yml"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: 0640
    validate: "{{ prometheus_install_path }}/promtool check config %s"
  notify: reload prometheus

- name: get avahi local hosts and ips
  shell: |
    if [[ {{ item }} == *.local ]]
    then
      set -o pipefail getent hosts {{ item }}
    else
      set -o pipefail getent hosts {{ item }}.local
    fi
  args:
    executable: "/bin/bash"
  loop: "{{ groups['all'] }} + {{ prometheus_metrics_job_targets }}"
  register: hosts_ips
  changed_when: no
  when: not item | regex_search('\d+\.\d+\.\d+\.\d+')

- name: add the hosts and ips to /etc/hosts
  become: yes
  lineinfile:
    dest: "/etc/hosts"
    regex: "{{ item.stdout | regex_replace(' +', ' ') }}"
    line: "{{ item.stdout | regex_replace(' +', ' ') }}"
    insertafter: "127.0.0.1 localhost"
    state: present
  loop: "{{ hosts_ips.results }}"
  when: item.stdout is defined and item.stdout
