---

- name: Template the blackbox_exporter_targets.yml
  become: true
  become_user: "{{ prometheus_user }}"
  ansible.builtin.template:
    src: "blackbox_exporter_targets.json.j2"
    dest: "{{ prometheus_blackbox_exporter_targets_json_file_sd_path }}"
    group: "{{ prometheus_group }}"
    mode: "0640"
