---

- name: Get the deb architecture
  ansible.builtin.command: dpkg --print-architecture
  register: deb_architecture
  changed_when: false

- name: Download prometheus
  become: true
  become_user: "{{ prometheus_user }}"
  ansible.builtin.unarchive:
    src: "{{ prometheus_download_url }}"
    dest: "/tmp"
    remote_src: yes

- name: Remove currently installed prometheus version
  become: true
  ansible.builtin.file:
    path: "{{ prometheus_install_path }}"
    state: absent

- name: Rename prometheus directory
  become: true
  ansible.builtin.command: "mv /tmp/prometheus-{{ prometheus_version }}.linux-{{ deb_architecture.stdout }} {{ prometheus_install_path }}"
  args:
    creates: "{{ prometheus_install_path }}"
  notify: Restart prometheus

- name: Set permissions on prometheus_install_path
  become: true
  ansible.builtin.file:
    path: "{{ prometheus_install_path }}"
    recurse: yes
    mode: "0755"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
  notify: Restart prometheus
