---

- name: unarchive prometheus
  become: yes
  become_user: "{{ prometheus_user }}"
  unarchive:
    src: "{{ prometheus_download_url }}"
    dest: "/tmp"
    remote_src: yes

- name: copy prometheus and promtool binaries
  become: yes
  become_user: "{{ prometheus_user }}"
  copy:
    src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}"
    dest: "{{ prometheus_home }}/{{ item }}"
    remote_src: yes
    mode: 0755
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
  loop:
    - prometheus
    - promtool
  notify:
    - restart prometheus
