---

- name: get the deb architecture
  command: dpkg --print-architecture
  register: deb_architecture
  changed_when: false

- name: Download prometheus
  become: true
  become_user: "{{ prometheus_user }}"
  unarchive:
    src: "{{ prometheus_download_url }}"
    dest: "/tmp"
    remote_src: yes

- name: Remove currently installed prometheus version
  become: true
  file:
    path: "{{ prometheus_install_path }}"
    state: absent

- name: rename prometheus directory
  become: true
  command: "mv /tmp/prometheus-{{ prometheus_version }}.linux-{{ deb_architecture.stdout }} {{ prometheus_install_path }}"
  args:
    creates: "{{ prometheus_install_path }}"
  notify: restart prometheus

- name: set permissions on prometheus_install_path
  become: true
  file:
    path: "{{ prometheus_install_path }}"
    recurse: yes
    mode: 0755
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
  notify: restart prometheus
