---

- name: ls the rules files
  command: "ls {{ role_path }}/files/rules/"
  delegate_to: 127.0.0.1
  register: "ls_rules_files"
  changed_when: no

- name: create list of rules files
  set_fact:
    rules_files: "{{ ls_rules_files.stdout_lines }}"

- name: copy the rule files
  become: yes
  copy:
    src: "rules/{{ item }}"
    dest: "{{ prometheus_rules_config_path }}"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: 0755
  notify: reload prometheus
  loop: "{{ rules_files }}"
