---

- name: Ls the rules files
  ansible.builtin.command: "ls {{ role_path }}/files/{{ rule_type }}_rules/"
  delegate_to: 127.0.0.1
  register: "ls_rules_files"
  changed_when: no

- name: Create list of rules files
  ansible.builtin.set_fact:
    rules_files: "{{ ls_rules_files.stdout_lines }}"

- name: Copy the rule files
  become: true
  ansible.builtin.copy:
    src: "{{ rule_type }}_rules/{{ item }}"
    dest: "{{ lookup('vars', 'prometheus_' ~ rule_type ~ '_rules_config_path') }}"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: "0755"
  notify: Reload prometheus
  loop: "{{ rules_files }}"
