---

- name: Install required packages
  become: true
  ansible.builtin.apt:
    name: "procps"
    state: present

- name: Create prometheus group
  become: true
  ansible.builtin.group:
    name: "{{ prometheus_group }}"
    system: yes
    state: present

- name: Create prometheus user
  become: true
  ansible.builtin.user:
    name: "{{ prometheus_user }}"
    shell: "/usr/sbin/nologin"
    home: "{{ prometheus_install_path }}"
    create_home: no
    system: yes
    group: "{{ prometheus_group }}"
    state: present

- name: Create prometheus base paths
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ prometheus_base_path }}"
    - "{{ prometheus_base_config_path }}"
