---

- name: install required packages
  become: yes
  apt:
    name: "procps"
    state: present

- name: create prometheus group
  become: yes
  group:
    name: "{{ prometheus_group }}"
    system: yes
    state: present

- name: create prometheus user
  become: yes
  user:
    name: "{{ prometheus_user }}"
    shell: "/usr/sbin/nologin"
    home: "{{ prometheus_install_path }}"
    create_home: no
    system: yes
    group: "{{ prometheus_group }}"
    state: present

- name: create prometheus base paths
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  loop:
    - "{{ prometheus_base_path }}"
    - "{{ prometheus_base_config_path }}"
