---

prometheus_node_exporter_user: "prometheus_node_exporter"
prometheus_node_exporter_group: "prometheus_node_exporter"
prometheus_node_exporter_home: "/opt/prometheus_node_exporter"
prometheus_node_exporter_config_path: "/etc/prometheus_node_exporter/config"
prometheus_node_exporter_version: 1.0.1
prometheus_node_exporter_download_url: "https://github.com/prometheus/node_exporter/releases/download/v{{ prometheus_node_exporter_version }}/node_exporter-{{ prometheus_node_exporter_version }}.linux-amd64.tar.gz"
prometheus_node_exporter_web_listen_port: "9100"
prometheus_node_exporter_web_listen_address: "0.0.0.0:{{ prometheus_node_exporter_web_listen_port }}"
prometheus_node_exporter_enabled_collectors:
  - arp
  - bonding
  - cpu
  - diskstats
prometheus_node_exporter_disabled_collectors: []
