---

prometheus_node_exporter_user: "prometheus_node_exporter"
prometheus_node_exporter_group: "prometheus_node_exporter"
prometheus_node_exporter_home: "/opt/prometheus_node_exporter"
prometheus_node_exporter_config_path: "/opt/prometheus_node_exporter/config"
prometheus_node_exporter_version: 1.0.1
prometheus_node_exporter_web_listen_port: "9100"
prometheus_node_exporter_web_listen_address: "0.0.0.0:{{ prometheus_node_exporter_web_listen_port }}"
prometheus_node_exporter_enabled_collectors:
  - arp
  - bonding
  - cpu
  - diskstats
prometheus_node_exporter_disabled_collectors: []
