---

- name: Create gotify configuration directory
  become: true
  ansible.builtin.file:
    path: "{{ gotify_config_path }}"
    state: directory
    owner: "{{ gotify_user }}"
    group: "{{ gotify_group }}"
    mode: "0755"

- name: Configure gotify
  become: true
  ansible.builtin.template:
    src: "gotify.yml.j2"
    dest: "{{ gotify_config_file_path }}"
    owner: "{{ gotify_user }}"
    group: "{{ gotify_group }}"
    mode: "0640"
  notify: Restart gotify
