---

- name: Get the deb architecture
  ansible.builtin.command: dpkg --print-architecture
  register: deb_architecture
  changed_when: false

- name: Create the gotify_install_path dir
  become: true
  ansible.builtin.file:
    path: "{{ gotify_install_path }}"
    owner: "{{ gotify_user }}"
    group: "{{ gotify_group }}"
    state: directory
    mode: "0755"

- name: Download and unarchive gotify
  become: true
  ansible.builtin.unarchive:
    src: "{{ gotify_download_url }}"
    dest: "{{ gotify_install_path }}"
    owner: "{{ gotify_user }}"
    group: "{{ gotify_group }}"
    remote_src: yes

- name: Template the version file
  become: true
  ansible.builtin.template:
    src: version.j2
    dest: "{{ gotify_version_file_path }}"
    owner: "{{ gotify_user }}"
    group: "{{ gotify_group }}"
    mode: "0644"
