---

- name: create service file
  become: yes
  template:
    src: gotify.service.j2
    dest: /etc/systemd/system/gotify.service
    owner: root
    group: root
    mode: 0644
  notify: restart gotify

- name: enable and start gotify
  become: yes
  service:
    daemon_reload: yes
    name: gotify
    state: started
    enabled: yes
