---

- name: Create service file
  become: true
  ansible.builtin.template:
    src: gotify.service.j2
    dest: /etc/systemd/system/gotify.service
    owner: root
    group: root
    mode: "0644"
  notify: Restart gotify

- name: Enable and start gotify
  become: true
  ansible.builtin.service:
    daemon_reload: yes
    name: gotify
    state: started
    enabled: yes
