---

- name: stat gotify version file
  stat:
    path: "{{ gotify_version_file_path }}"
  register: gotify_version_file_stat

- name: slurp gotify version file
  slurp:
    path: "{{ gotify_version_file_path }}"
  register: gotify_version_file
  when: gotify_version_file_stat.stat.exists

- name: set fact to install gotify
  set_fact:
    install_gotify: "{{ not gotify_version_file_stat.stat.exists or gotify_version_file['content'] | b64decode | trim != gotify_version }}"
