---

- name: Restart prometheus_alertmanager
  become: true
  ansible.builtin.service:
    name: prometheus_alertmanager
    state: restarted

- name: Restart prometheus_alertmanager_gotify_bridge
  become: true
  ansible.builtin.service:
    name: prometheus_alertmanager_gotify_bridge
    state: restarted
