---

- name: restart prometheus_alertmanager
  become: true
  service:
    name: prometheus_alertmanager
    state: restarted

- name: restart prometheus_alertmanager_gotify_bridge
  become: true
  service:
    name: prometheus_alertmanager_gotify_bridge
    state: restarted
