---

- name: Import install tasks
  ansible.builtin.import_tasks: install.yml
- name: Include nfs import tasks
  ansible.builtin.include_tasks: nfs_import.yml
  loop: "{{ nfs_client_imports }}"
  loop_control:
    loop_var: "nfs_import"
