---

- name: Create the local dirs
  become: true
  ansible.builtin.file:
    path: "{{ nfs_import.local_dir }}"
    state: "{% if nfs_import.state == 'absent' %}absent{% else %}directory{% endif %}"
    mode: "{{ nfs_import.mode | d('0755') }}"

- name: Add the imports to fstab
  become: true
  ansible.posix.mount:
    src: "{{ nfs_import.nfs_server }}:{{ nfs_import.remote_dir }}"
    path: "{{ nfs_import.local_dir }}"
    fstype: nfs
    opts: user,auto
    state: "{{ nfs_import.state | default('mounted') }}"
