---

- name: converge
  hosts: all
  vars:
    apache_vhosts_config:
      - { name: molecule_proxy_pass_http, server_name: "molecule_proxy_pass_http.random.url", listen_port: "9003", template: "proxy_pass" }
      - { name: molecule_proxy_pass_https, server_name: "molecule_proxy_pass_https.random.url", listen_port: "9003", template: "proxy_pass", enable_ssl: true }
      - { name: molecule_document_root_http, server_name: "molecule_document_root_http.random.url", document_root: "/var/www/html/", template: "document_root" }
      - { name: molecule_document_root_https, server_name: "molecule_document_root_https.random.url", document_root: "/var/www/html/", template: "document_root", enable_ssl: true }
    skip_apache_vhosts_reload_handler: true
    # To test the ssl configuration
    ssl_cert:
      dir: "/etc/ssl/molecule"
      key:
        filename: "molecule.key"
      crt:
        filename: "molecule.crt"

  roles:
    - { role: apache_vhosts }
