---

dependency:
  name: galaxy
  options:
    ignore_warnings: true
driver:
  name: docker
platforms:
  - name: debian-bookworm-${MOLECULE_SCENARIO_NAME:-instance}
    image: debian:bookworm
    privileged: true
    pre_build_image: false
    command: "/lib/systemd/systemd"
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    cgroupns_mode: host
provisioner:
  name: ansible
  log: True
  config_options:
    defaults:
      callbacks_enabled: timer, profile_tasks
      stdout_callback: debug
      interpreter_python: auto_silent
  env:
    PY_COLORS: '1'
    ANSIBLE_FORCE_COLOR: '1'
    ANSIBLE_ROLES_PATH: '../../roles'
verifier:
  name: testinfra
  options:
    # We specify the connection and hosts here so the pytest runs faster.
    # Without these options pytest takes about 10 - 20 times longer to run
    connection: docker
    hosts: root@debian-bookworm-${MOLECULE_SCENARIO_NAME:-instance}
scenario:
  create_sequence:
    - create
  check_sequence:
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - create
    - prepare
    - converge
    - idempotence
  destroy_sequence:
    - destroy
  test_sequence:
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - destroy
