---

- name: Start and enable postgresql
  become: true
  ansible.builtin.service:
    name: postgresql
    state: started
    enabled: yes

- name: Create the database
  become: true
  become_user: postgres
  community.postgresql.postgresql_db:
    name: "{{ miniflux_db_name }}"

- name: Create the database user
  become: true
  become_user: postgres
  community.postgresql.postgresql_user:
    name: "{{ miniflux_db_user }}"
    password: "{{ miniflux_db_password }}"

- name: Grant all privs to the database user on the database
  become: true
  become_user: postgres
  community.postgresql.postgresql_privs:
    database: "{{ miniflux_db_name }}"
    state: present
    privs: ALL
    roles: "{{ miniflux_db_user }}"
    type: database

- name: Grant privs to the database user on schema public
  become: true
  become_user: postgres
  community.postgresql.postgresql_privs:
    database: "{{ miniflux_db_name }}"
    state: present
    privs: ALL
    roles: "{{ miniflux_db_user }}"
    type: schema
    objs: public
