---

- name: Add miniflux repository
  become: true
  apt_repository:
    repo: "deb [trusted=yes] https://repo.miniflux.app/apt/ * *"
    filename: "miniflux"
    state: present

- name: install required packages
  become: true
  apt:
    name: "{{ miniflux_required_packages }}"
    state: present
    install_recommends: no
