---

prometheus_group: "prometheus"
prometheus_user: "prometheus"
prometheus_home: "/opt/prometheus"
prometheus_config_dir: "/opt/prometheus/config"
prometheus_version: 2.19.2
prometheus_web_listen_address: "0.0.0.0:9090"
prometheus_storage_retention: "30d"
