---

- name: Restart prometheus
  become: true
  ansible.builtin.service:
    name: prometheus
    state: restarted

- name: Reload prometheus
  become: true
  ansible.builtin.service:
    name: prometheus
    state: reloaded
