---

- hosts: all
  roles:
    - { role: apt, tags: [ "apt" ] }
    - { role: base_setup, tags: [ "base_setup" ] }
    - { role: node_exporter, tags: [ "node_exporter" ] }
    - { role: resolvconf, tags: [ "resolvconf" ] }
