---

- import_playbook: base.yml

- hosts: downloader
  roles:
    - { role: openvpn, tags: [ 'openvpn' ] }
    - { role: sabnzbd, tags: [ "sabnzbd" ] }
    - { role: nfs_server, tags: [ 'nfs_server' ] }
    - { role: transmission, tags: [ 'transmission' ] }
