---

- import_playbook: base.yml

- hosts: link
  roles:
    - role: ssl_cert
      tags: [ ssl_cert ]
    - role: apache
      tags: [ apache ]
    - role: apache_vhosts
      tags: [ apache, apache_vhosts ]
    - role: miniflux
      tags: [ miniflux ]
    - role: gotify
      tags: [ gotify ]
    - role: vikunja
      tags: [ vikunja ]
