---

- name: Import the base playbook
  import_playbook: base.yml

- name: Play for merovingian host
  hosts: merovingian
  roles:
    - role: ssl_cert
      tags: [ "ssl_cert" ]
    - role: apache
      tags: [ "apache" ]
    - role: apache_vhosts
      tags: [ "apache", "apache_vhosts" ]
    - role: prometheus
      tags: [ "prometheus", "prometheus_controller" ]
    - role: prometheus_alertmanager
      tags: [ "prometheus", "prometheus_alertmanager" ]
    - role: grafana
      tags: [ "grafana" ]
    - role: prometheus_blackbox_exporter
      tags: [ "prometheus", "prometheus_blackbox_exporter" ]
