---

- import_playbook: base.yml

- hosts: monitoring

  roles:
    - { role: prometheus, tags: [ "prometheus" ] }
    - { role: grafana, tags: [ "grafana" ] }
    - { role: blackbox_exporter, tags: [ "blackbox_exporter" ] }
