---

- import_playbook: base.yml

- hosts: searcher
  roles:
    - { role: openvpn, tags: [ "openvpn" ] }
    - { role: nfs_client, tags: [ "nfs_client" ] }
    - { role: medusa, tags: [ "medusa" ] }
