---

- import_playbook: base.yml

- hosts: searcher
  roles:
    - { role: apache, tags: [ "apache" ] }
    - { role: apache_vhosts, tags: [ "apache", "apache_vhosts" ] }
    - { role: openvpn, tags: [ "openvpn" ] }
    - { role: nfs_client, tags: [ "nfs_client" ] }
    - { role: medusa, tags: [ "medusa" ] }
    - { role: ssl_cert, tags: [ "ssl_cert" ] }
