---

- import_playbook: base.yml

- hosts: trinity
  roles:
    - { role: ssl_cert, tags: [ "ssl_cert" ] }
    - { role: apache, tags: [ "apache" ] }
    - { role: apache_vhosts, tags: [ "apache", "apache_vhosts" ] }
    - { role: pihole, tags: [ "pihole" ] }
    - { role: gotify, tags: [ "gotify" ] }
