---

- name: configure openvpn
  become: true
  lineinfile:
    path: "/etc/default/openvpn"
    line: "AUTOSTART=\"all\""
    regexp: "^(#)?AUTOSTART=\"all\""
    state: present

- name: create openvpn config file
  become: true
  template:
    src: "{{ openvpn_name }}.ovpn.j2"
    dest: "/etc/openvpn/{{ openvpn_name }}.conf"
    mode: 0640
  notify: restart openvpn

- name: create openvpn_auth_user_pass_file_path
  become: true
  template:
    src: auth_user_pass.j2
    dest: "{{ openvpn_auth_user_pass_file_path }}"
    mode: 0600
  notify: restart openvpn

- name: start and enable openvpn
  become: true
  service:
    name: openvpn
    enabled: yes
    state: started

- name: "start and enable openvpn {{ openvpn_name }}"
  become: true
  systemd:
    name: "openvpn@{{ openvpn_name }}"
    enabled: yes
    state: started
    daemon_reload: yes
