---

- name: Configure openvpn
  become: true
  ansible.builtin.lineinfile:
    path: "/etc/default/openvpn"
    line: "AUTOSTART=\"all\""
    regexp: "^(#)?AUTOSTART=\"all\""
    state: present

- name: Create openvpn config file
  become: true
  ansible.builtin.template:
    src: "{{ openvpn_name }}.ovpn.j2"
    dest: "/etc/openvpn/{{ openvpn_name }}.conf"
    mode: "0640"
  notify: Restart openvpn

- name: Create openvpn_auth_user_pass_file_path
  become: true
  ansible.builtin.template:
    src: auth_user_pass.j2
    dest: "{{ openvpn_auth_user_pass_file_path }}"
    mode: "0600"
  notify: Restart openvpn

- name: Start and enable openvpn
  become: true
  ansible.builtin.service:
    name: openvpn
    enabled: yes
    state: started

- name: Start and enable openvpn
  become: true
  ansible.builtin.systemd:
    name: "openvpn@{{ openvpn_name }}"
    enabled: yes
    state: started
    daemon_reload: yes
