---

- name: allow user {{ pihole_user }} to execute pihole as root without password
  become: true
  copy:
    dest: "/etc/sudoers.d/pihole"
    validate: /usr/sbin/visudo -csf %s
    content: |
      {{ pihole_user }} ALL=(ALL) NOPASSWD:/usr/local/bin/pihole
    mode: 0440

- name: template the update_adlists script
  become: true
  template:
    src: "update_adlists.j2"
    dest: "{{ pihole_config_path }}/update_adlists"
    owner: "{{ pihole_user }}"
    group: "{{ pihole_group }}"
    mode: 0644

- name: add a cronjob to run update_adlists script
  become: true
  cron:
    name: "update adlists"
    user: "{{ pihole_user }}"
    minute: "0"
    hour: "3"
    day: "7"
    job: "bash {{ pihole_config_path }}/update_adlists"

- name: trigger the update_adlists script if we have just installed or updated pihole
  become: true
  command: bash {{ pihole_config_path }}/update_adlists
  args:
    executable: "/bin/bash"
  when: install_pihole
