---

- name: template the dns records
  become: yes
  template:
    src: "dns_records.j2"
    dest: "{{ pihole_config_path }}/custom.list"
    owner: "{{ pihole_user }}"
    group: "{{ pihole_group }}"
    mode: 0644
  notify: reload dns
