---


- name: 'Template the setupVars for unattended install'
  become: yes
  template:
    src: setupVars.conf.j2
    dest: /etc/pihole/setupVars.conf
    owner: "{{ pihole_user }}"
    group: "{{ pihole_group }}"
    mode: 0644

- name: download the pihole installer
  become: yes
  get_url:
    url: "https://install.pi-hole.net"
    dest: "/tmp/pihole-install.sh"
    mode: 0755
  when: run_pihole_installer

- name: run pihole installer
  become: yes
  command: "./pihole-install.sh --unattended"
  args:
    executable: "/bin/bash"
    chdir: "/tmp"
  environment:
    TERM: "xterm"
  when: run_pihole_installer
