---

- name: 'Template the setupVars for unattended install'
  become: true
  template:
    src: setupVars.conf.j2
    dest: /etc/pihole/setupVars.conf
    owner: "{{ pihole_user }}"
    group: "{{ pihole_group }}"
    mode: 0644

- name: download the pihole installer
  become: true
  get_url:
    url: "https://install.pi-hole.net"
    dest: "/tmp/pihole-install.sh"
    mode: 0755

- name: run pihole installer
  become: true
  command: "./pihole-install.sh --unattended"
  args:
    chdir: "/tmp"
  environment:
    TERM: "xterm"
  tags: skip_ansible_lint
