---

- name: install required packages
  become: true
  apt:
    name: "{{ pihole_required_packages }}"
    state: present
    install_recommends: no

- name: add pihole group
  become: true
  group:
    name: "{{ pihole_group }}"
    state: present

- name: create pihole user
  become: true
  user:
    name: "{{ pihole_user }}"
    home: "/etc/pihole" # can't change this as the setupVars need to be in this folder for the --unattended to work
    create_home: yes
    system: yes
    group: "{{ pihole_group }}"
    state: present
